### ISSUE TITLE
[cosmetic-ui] bad content alignment (v2) + bonus

### ISSUE THREAD

**Issue by mattia-b89** [fflewddur/tophat#171]
_(since I cannot reopen the original issue (https://github.com/fflewddur/tophat/issues/168), I have to open a new one)_

---
newest v20 fixes alignment in the memory panel, not for the network one,  
(see screenshot below);  

![Image](https://github.com/user-attachments/assets/3891e51a-dc14-4eb5-bc42-df687583c6ef)

---
BONUS: I noticed network panel's title alignment changes over time: from centre-aligned to left-aligned!!  
(see screenshot below);  

![Image](https://github.com/user-attachments/assets/f0cf4202-c5e4-48b7-8531-b44aeea0317b)

AND, I suggest to better "highlight" panel's title (for all panels):  
previously, title was bold-white, immediately impressive,  
now it's grey and definitively not-bold... almost hard to recognize it as title... I guess titles should immediately stand-out, and this is not the case

**Comment by fflewddur** [comment]
Thanks for reporting this! I've fixed the center-aligned stacked labels. I'm not sure why you're seeing that odd alignment for the menu itself. Have you noticed anything that seems to trigger that?

I intentionally dimmed the menu headers. The idea is to focus on the content rather than the menu chrome.

**Comment by mattia-b89** [comment]
> [...] Have you noticed anything that seems to trigger that?

Fortunately or unfortunately, I am not able to reproduce it. It has been a _solo_
So, I'll be back when I test the new version, if needed 😉

**Comment by fflewddur** [comment]
Sounds good, I'll close this for now. You should be able to re-open the issue if needed.

**Comment by fflewddur** [comment]
Ah, sorry about the confusion there, I didn't realize re-opening issues wasn't a public feature. Commenting like this works just as well, so thanks for letting me know!

I've been trying to replicate this on my systems but still have never seen it. My best guess is that another extension on your system uses the same CSS class names for something in that menu, which is adding extra right padding/margin. I'm going to refactor the CSS class names so that they are all prefixed with 'tophat-', and we'll see if that resolves this.

If you can identify any repeatable steps to reproduce this issue, that would also be really helpful.

**Comment by mattia-b89** [comment]
I tried by disabling all extensions except TopHat but nothing changed;  
I tried disabling "Large Text" option in Accessibility (gnome's settings) and this helped:  
you can notice the change from the screenshot below  

_To be precise, without that "Large Text" option enabled, I can still see a very little mis-alignment on the right as well_

![Image](https://github.com/user-attachments/assets/bd6ccf94-04bf-483a-a346-eb78f20d031c)
