### ISSUE TITLE
Bug Report: gnome-shell crashes when a network drive disconnects

### ISSUE THREAD

**Issue by aljazzair** [fflewddur/tophat#76]
**OS Manjaro Arch**
uname -a
`Linux computer 6.1.11-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Feb  9 14:03:23 UTC 2023 x86_64 GNU/Linux`

**Gnome Shell**
gnome-shell --version
`GNOME Shell 43.2`

**Tophat**: 
latest version available through Gnome Extensions website.

**Summary**: 
When tophat is enabled, a gnome-shell crash occurs. 
When tophat is disabled this crash does not occur. 
A more detailed description of the issue is provided below.

**Details**:
First off, thank you for creating this fantastic extension.
I have been using it for a long time without issue.

Recently some enhancements were introduced around disk monitoring.
I _suspect_ those enhancements have to do with this bug.
Somehow this extension is now causing gnome-shell to crash on my system.

I have a VM set up to serve media content in my LAN. 
One of the disks attached to this VM is accessed by the host through SMB. 
It is a ZFS filesystem.
When the VM is running, the host can access the content using SMB.
When the VM is shutdown, the host no longer has access to this disk through SMB.

In TOPHAT, I tried switchingthe option "show the disk monitor" on or off, to no avail.

Every time I shutdown the VM described above, and tophat is enabled, gnome shell crashes.
Starting the VM restores gnome-shell operation.
If I turn off the Top hat extension this crash does not occur.
This issue started a few weeks ago, I do not remember exactly when. 
I just discovered this crash only happens when tophat is enabled.

Please let me know if additional logs are useful to resolve, I would be more than happy to assist in resolving this issue, if possible.
Thank you.

EDIT: partial log around the crash, file updated:
`journalctl -p4` 
[partialog.txt](https://github.com/fflewddur/tophat/files/10735406/partialog.txt)

**Comment by fflewddur** [comment]
Thanks for reporting this! I think I found + fixed the cause of the shell crashes based on your log file, but haven't been able to replicate the crash myself. Could you try out the attached version of TopHat to see if it solves the problem? To install it, unzip the archive to ~/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/, then log out and back in.

[tophat@fflewddur.github.io.shell-extension.zip](https://github.com/fflewddur/tophat/files/10738864/tophat%40fflewddur.github.io.shell-extension.zip)

**Comment by fflewddur** [comment]
Thanks @aljazzair, sorry this didn't fix the issue. I'm still trying to replicate this directly, but it seems my particular network setup (only wireless, no ethernet connection) doesn't support bridging in the way that yours is setup, at least with KVM. Are you using KVM, virtualbox, or something else for your VM configuration?

Also, could you try disabling TopHat's network monitor in addition to its disk monitor? Some of the lines in the log make me wonder if it's freezing when the network config changes, rather than when the mount point goes away.

**Comment by fflewddur** [comment]
Hi @aljazzair, I've been able to replicate this issue with a simpler setup:

- Share a folder from a Windows machine
- Mount the shared folder from a Linux machine running Tophat
- Shut down the Windows file server or disconnect it from the network (but don't unmount the share from Linux first)

For me, this set of actions consistently locks up the GNOME Shell. I've traced the issue to libgtop, which seems to hang when asked to get filesystem info for a mounted-but-unavailable filesystem. I've fixed TopHat to refresh its list of mounted shares before checking current filesystem usage, but when the share has disconnected but not yet unmounted, it will still hang. I'm re-opening this issue until I can figure out a fix. Thanks again for reporting this--it's certainly not unique to your setup!

**Comment by erinaceous** [comment]
I also have this issue, with a similar setup - narrowed it down to TopHat!

* GNOME freezes on me when I lose network connection - ie. I can unplug the ethernet cable and as soon as `dmesg -w` shows "link is down", desktop freezes completely
* I also run virtual machines using libvirt (KVM) and I have set up a bridge network.  So, the network connection GNOME can see is `bridge0`, which is the one which gets an IP, and depends on "slave" `enp8s0` for the physical link.
* I have an NFS mount to another server on my network mounted at `/everything`.  It's "soft" mounted so should I lose network then I/O to it shouldn't hang indefinitely - it previously was mounted `hard,intr`  (hard but with interrupts) as I thought that might fix the freezing thing.
* I've disabled NetworkManager "connectivity checking", `[connectivity] enabled=false` in a config file - that at least improved the GNOME freezes, it now only hangs for a second or so after plugging the ethernet back in, it used to hang until the full connectivity check was finished (which could take like a minute).
* Disabling the TopHat extension fixed the freezing when the network was disconnected.
* With TopHat enabled, switching off the disk and network monitors did _not_ fix the freezing.
* Fedora 38, GNOME 44.3 on Wayland, kernel 6.4.6-200, libgtop 2.41.1 installed, TopHat v11

**Comment by rokiden** [comment]
Ubuntu 22.04
GNOME Shell 42.9
Wired network and NFS share mounted.
Only processor and network monitoring enabled in TopHat.

Disconnecting ethernet cable or stopping NFS server causes desktop freeze, nothing works, ctrl+alt+f* too.
Disabling TopHat solved problem.

**Comment by apedicdev** [comment]
Still not sure 100% but seems when I use it, gnome shell also crashes for me when logging in back after suspend. All windows open are gone. I'm on Manjaro too

**Comment by fflewddur** [comment]
This issue has been resolved in the v16 release of TopHat.
